basePath: /api/v1
definitions:
  auth.AuthModel:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.AuthResponse:
    properties:
      data: {}
      refresh_token:
        type: string
      token:
        type: string
    type: object
  auth.LogoutRequest:
    properties:
      refresh_token:
        example: your-refresh-token
        type: string
    type: object
  roles.AssignRoleModel:
    properties:
      role_id:
        type: string
      user_id:
        type: string
    type: object
  roles.RoleModel:
    properties:
      id:
        type: string
      name:
        type: string
      permission:
        items:
          type: string
        type: array
    type: object
  roles.RoleUpdateModel:
    properties:
      name:
        type: string
      permission:
        items:
          type: string
        type: array
    type: object
  shared.DataWithPagination:
    properties:
      items: {}
      paging:
        $ref: '#/definitions/shared.Pagination'
    type: object
  shared.Pagination:
    properties:
      limit:
        type: integer
      page:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  shared.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  users.UserCreateModel:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    type: object
  users.UserModel:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  users.UserModelResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  users.UserUpdateModel:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
host: localhost:7000
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is a sample server.
  title: Starter Golang API
  version: "1.0"
paths:
  /auth/access-token:
    post:
      consumes:
      - application/json
      description: Renew token an user
      parameters:
      - description: Logout payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shared.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Renew token
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login an user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.AuthModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth.AuthResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      summary: Login
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout an user
      parameters:
      - description: Logout payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shared.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register an user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserCreateModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  $ref: '#/definitions/users.UserCreateModel'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      summary: Register
      tags:
      - auth
  /roles:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all roles
      parameters:
      - default: 10
        description: total data per-page
        in: query
        minimum: 1
        name: limit
        type: integer
      - default: 1
        description: page
        in: query
        minimum: 1
        name: page
        type: integer
      - description: keyword
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/shared.DataWithPagination'
                  - properties:
                      items:
                        items:
                          $ref: '#/definitions/roles.RoleModel'
                        type: array
                    type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Get all roles
      tags:
      - roles
    post:
      consumes:
      - application/json
      description: Create an role
      parameters:
      - description: role Data
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/roles.RoleUpdateModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/shared.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Create an role
      tags:
      - roles
  /roles/{id}:
    delete:
      consumes:
      - application/json
      description: Delete role by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete role
      tags:
      - roles
    get:
      consumes:
      - application/json
      description: Retrieve a role by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  $ref: '#/definitions/roles.RoleModel'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Get all roles
      tags:
      - roles
    put:
      consumes:
      - application/json
      description: Update role
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: role Data
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/roles.RoleUpdateModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/shared.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Update role
      tags:
      - roles
  /roles/assign:
    post:
      consumes:
      - application/json
      description: Assign an role
      parameters:
      - description: role Data
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/roles.AssignRoleModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/shared.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Assign an role
      tags:
      - roles
  /roles/unassign:
    post:
      consumes:
      - application/json
      description: UnAssign an role
      parameters:
      - description: role Data
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/roles.AssignRoleModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/shared.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: UnAssign an role
      tags:
      - roles
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all users
      parameters:
      - default: 10
        description: total data per-page
        in: query
        minimum: 1
        name: limit
        type: integer
      - default: 1
        description: page
        in: query
        minimum: 1
        name: page
        type: integer
      - description: keyword
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/shared.DataWithPagination'
                  - properties:
                      items:
                        items:
                          $ref: '#/definitions/users.UserModelResponse'
                        type: array
                    type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create an user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserCreateModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/shared.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Create an user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Retrieve a user by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  $ref: '#/definitions/users.UserModel'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserUpdateModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/shared.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shared.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/shared.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/shared.Response'
      security:
      - ApiKeyAuth: []
      summary: Update user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
